### ISSUE TITLE
[BUG] decodesau

### ISSUE THREAD

**Issue by shikulja** [minexew/Soft3D-RE#10]
When decoding, SAU throws an error:

> Guessed nibble order (12) from extension: no byteswap needed
> Reading input file...
> Decoding SAU input...
> Writing the output (1884578 PCM frames)...
> Finished!

At the same time, I checked both keys "-n", "--no-byteswap". But the result is the same.
This is probably just a bug in the logic of work. and the error is false since the audio is decoded.

Example of my script:

> 	mkdir dec_sau
> 		for /f %%x in ('"dir /s /b *.sau"') do py decodesau.py -n "%%x" "dec_sau\%%~nx.wav"

_(tested on symbian version)_

**Comment by Yoti** [comment]
Which version (exact one) are you using?

**Comment by shikulja** [comment]
@Yoti 
7_Days_Salvation_English_v1.0.sis 
CRC32 04108EAF
This is a port of the Chinese version into English, as far as I understand.

[example_sau.zip](https://github.com/minexew/Soft3D-RE/files/9938953/example_sau.zip)
[readme.txt](https://github.com/minexew/Soft3D-RE/files/9939060/readme.txt)

**Comment by ostrosablin** [comment]
But I don't see any error there. If you mean this:

`Guessed nibble order (12) from extension: no byteswap needed`

It's not an error at all. It's just an informational message that indicates that decodesau has automatically inferred from file extension that it's has direct-ordered (12) nibbles and that it doesn't need to be byteswapped. So, --no-byteswap is not needed at all for SAU files, they're automatically detected and properly handled.

If file had WAR extension, that would've meant it has reverse-ordered nibbles (21) and it's necessary to convert it into SAU first, then into WAV.

So, in your case, you don't really need to use -n or --no-byteswap. These options were only meant for files that don't have extension and their format is not really known.

**Comment by shikulja** [comment]
@ostrosablin 
thanks for the clarification. Now I can remove the -n option with peace of mind
