### ISSUE TITLE
stx conversion error

### ISSUE THREAD

**Issue by shikulja** [minexew/Soft3D-RE#9]
Depending on whether I choose the path to a directory, I get error. Failed to get it to work

py stx.py stx.py .\res\common .\dec_stx
py stx.py stx.py res\common dec_stx

usage: stx.py [-h] input output
stx.py: error: unrecognized arguments: .\dec_stx

usage: stx.py [-h] input output
stx.py: error: unrecognized arguments: dec_stx

C:\Users\admin\Desktop\EKA2L1\data\drives\e\System\apps\SevenDays>py stx.py res\common\ res\common\4
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\EKA2L1\data\drives\e\System\apps\SevenDays\stx.py", line 85, in <module>
    with open(args.input, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'res\\common'

C:\Users\admin\Desktop\EKA2L1\data\drives\e\System\apps\SevenDays>py stx.py res\common\zp_beijing_c.stx res\
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\EKA2L1\data\drives\e\System\apps\SevenDays\stx.py", line 86, in <module>
    image = load(f)
            ^^^^^^^
  File "C:\Users\admin\Desktop\EKA2L1\data\drives\e\System\apps\SevenDays\stx.py", line 26, in load
    type = ImageType(type)
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.240.0_x64__qbz5n2kfra8p0\Lib\enum.py", line 695, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.240.0_x64__qbz5n2kfra8p0\Lib\enum.py", line 1111, in __new__
    raise ve_exc
ValueError: 255 is not a valid ImageType

**Comment by shikulja** [comment]
`py stx.py stx.py .\res\common .\dec_stx`

usage: stx.py [-h] input output
stx.py: error: unrecognized arguments: .\dec_stx

**Comment by Yoti** [comment]
Do not write stx.py twice.

**Comment by shikulja** [comment]
@Yoti 
I'm sorry, I was too smart with copying
the error is still there.
(I have Administrator privileges)
<img width="675" alt="image" src="https://user-images.githubusercontent.com/3386359/200036816-14bb96db-8ab6-49ab-9834-87c699983949.png">

**Comment by Yoti** [comment]
There is no such FILE like res\common.

**Comment by shikulja** [comment]
@Yoti 
<img width="675" alt="image" src="https://user-images.githubusercontent.com/3386359/200052827-60c5c00f-8048-4498-a926-df3055644043.png">

I indicated all the paths I knew, to directories, full paths, the path to the file, and so on. I have already gone through seven circles of hell.
Even in two versions of Linux, there are other errors ..

**Comment by Yoti** [comment]
What you want to do? Try to open your test file (_alp is the alpha mask) with my viewer: https://github.com/minexew/Soft3D-RE/blob/master/Tools_Other/stxviewr.exe

**Comment by shikulja** [comment]
@Yoti 
I tried it, it doesn't work either.
I need to convert stx files and convert back from images

<img width="272" alt="image" src="https://user-images.githubusercontent.com/3386359/200058600-c5217bcd-6b01-45da-83d3-e5af8599c616.png">
<img width="165" alt="image" src="https://user-images.githubusercontent.com/3386359/200058951-9576dc71-9606-4d3f-b1cd-4375a43a955c.png">

**Comment by Yoti** [comment]
Files are broken or unsupported. I will check this in a few days.

**Comment by Yoti** [comment]
Which game version are you using?

**Comment by shikulja** [comment]
@Yoti 
7_Days_Salvation_English_v1.0.sis
CRC32 04108EAF
This is a port of the Chinese version into English, as far as I understand.
[readme.txt](https://github.com/minexew/Soft3D-RE/files/10033660/readme.txt)

**Comment by Yoti** [comment]
Yeah, this one was made by mr.nobody and pals. I looked at the textures from this sis the day before yesterday and everything was OK. Will recheck soon.

**Comment by Yoti** [comment]
Yeah, this is `extractspk.py` bug: files missing first byte. Use [this tool](https://github.com/minexew/Soft3D-RE/blob/master/Tools_Other/salvador_quick.exe) until it's fixed.

**Comment by shikulja** [comment]
@Yoti
I'm trying to decompress stx textures using stx.py (and decompress them back later)

.spk archive is already unpacked.

**Comment by Yoti** [comment]
Which tool you used to unpack res.spk? If you used extractspk.py than all your files are broken. You must unpack it again with provided Windows tool.

**Comment by shikulja** [comment]
@Yoti I used extractspk.py.
I tried salvador_quick.exe as you suggested, but it looks like stx.py still throws errors, errors related to path input parameters.

**Comment by Yoti** [comment]
Please share output log or screenshot.

**Comment by shikulja** [comment]
```
C:\7DS>python3 stx.py dj_frank_b.stx TEXdec\
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIL\Image.py", line 2331, in save
    format = EXTENSION[ext]
             ~~~~~~~~~^^^^^
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\7DS\stx.py", line 87, in <module>
    image.save(args.output)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIL\Image.py", line 2333, in save
    raise ValueError(f"unknown file extension: {ext}") from e
ValueError: unknown file extension:
```
<img width="668" alt="image" src="https://user-images.githubusercontent.com/3386359/202772727-593d0e87-ff1a-47ef-8631-8dc39206c170.png">

**Comment by shikulja** [comment]
@Yoti 
work with that parameters:
 stx.py dj_frank_b.stx output.png
Will test later.
How to encode back, it seems that this utility does not know how to do this?

**Comment by Yoti** [comment]
This repo only has unpackers and decoders as I know. May be you can find something there: https://www.cyberforum.ru/delphi-beginners/thread2669850.html
